#!/bin/bash
rake db:migrate &
rake db:migrate RAILS_ENV=test TEST_ENV_NUMBER=0 &
rake db:migrate RAILS_ENV=test TEST_ENV_NUMBER=1 &
rake db:migrate RAILS_ENV=test TEST_ENV_NUMBER=2 &
rake db:migrate RAILS_ENV=test TEST_ENV_NUMBER=3 &
rake db:migrate RAILS_ENV=test TEST_ENV_NUMBER=4 &
