#!/bin/bash
echo "PUSH to GITHUB"
git push origin master --force
echo "PUSH to HEROKU"
git push heroku master --force
echo "Migrate DB"
heroku rake db:migrate
echo "RESTART"
heroku restart
echo "RESET MATCHES"
heroku match:reset
heroku rake match:start_bot

