development: &development
  requester_stale_after: 5
  started_after: 5
  ended_after: 15 
  questions_per_match: 3

test:
  <<: *development
  requester_stale_after: 2
  started_after: 4 
  ended_after: 10

production: &development
  requester_stale_after: 5
  started_after: 15
  ended_after: 60
  questions_per_match: 20
