development: &development
  requester_stale_after: 50
  started_after: 5
  ended_after: 150
  questions_per_match: 3

test:
  <<: *development
  requester_stale_after: 6
  started_after: 3 
  ended_after: 15

production: &development
  requester_stale_after: 5
  started_after: 15
  ended_after: 60
  questions_per_match: 20
