development: &development
  requester_stale_after: 50
  user_inactive_after: 400
  started_after: 5
  ended_after: 150
  questions_per_match: 3
  users_per_match: 4
  waiting_slots_size: 10 # this slots size used to calculate number of users waiting for match, so that auto bot can be launched
  active_slots_size: 50 # this slots size used to store 50 very last active users of league
  questions_per_cache_block: 5 # number of questions will be preloaded in order to make sure user always have smooth experience doing match
  questions_refill_threshold: 3 # number of un-used questions remain in the cache to force another cache request
  status_recheck_interval: 1
  bot_life_time: 5
  bot_sleep_time_between_beats: 1
  bot_max_match_request_retries: 3
  bot_time_per_question: 5
  bot_correctness: 0.8
  fake_active_users_slot: 40

test:
  <<: *development
  requester_stale_after: 60
  started_after: 3 
  ended_after: 150

production: 
  <<: *development
  requester_stale_after: 5
  user_inactive_after: 300
  status_recheck_interval: 3
  started_after: 10
  ended_after: 120
  questions_per_match: 15
  bot_life_time: 60
