production:
  server: 
    - server-1:11211
    - server-2:11211
  nspace: prod
development: &development
  server: 
    - 127.0.0.1:11211
  nspace: dev
  username: dev
test:
  <<: *development
  nspace: test<%=(ENV["TEST_ENV_NUMBER"] || -1).to_i + 1%>
  username: test<%=(ENV["TEST_ENV_NUMBER"] || -1).to_i + 1%> 
