production:
  server: 
    - server-1:11211
    - server-2:11211
  namespace: prod
development: &development
  server: 
    - 127.0.0.1:11211
  namespace: dev
test:
  <<: *development
  namespace: test<%=(ENV["TEST_ENV_NUMBER"] || -1).to_i + 1%>
