development: &development
  name: dautri
  domain: dautri.net
  bot_domain: dautri.net
  chat: &chat
    server: "http://localhost:3500"
    client_js: "chat.js"
    mount_point: "chat"
    history_mount_point: "history"
    history_limit: 50
test:
  <<: *development

production:
  <<: *development
  chat:
    <<: *chat
    server: "http://chat.dautri.net:3500" 
